baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
#title: "Hugo-profile"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2

params:
  version: 3
  customCSS: false
  hitext: "Hi there! I'm"

  #favicon: "/images/fav.png"
  #description: "A high performance hugo theme for personal portfolio and blog."

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Mikael J. Gonsalves, Ph.D"
  namecolor: ffc107
  profession: "Dr. Psychology & Ethics, Data Analyst"
  github: "https://github.com/MikaelJG"
  gitlab: "https://gitlab.com"
  linkedin: "https://www.linkedin.com/in/mikael-j-gonsalves-ph-d-586260222/"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=H3Icf34AAAAJ&view_op=list_works&sortby=pubdate"
  email: "mailto:mjgonsalves@protonmail.com"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "Hi, again! I'm Mikael a passionate researcher in psychology and data science. Fan of all games, I'm working hard towards game user experience positions!"
  descripe_l2_person: "I work with R/RMarkdown, MOffice and JASP to understand users. Motivational interviews are my speciality! Currently learning a few tricks in python and SQL. You can find my works [here](#projects)"
  skills:
    - name: Motivational Interviews
      percentage: 95
    - name: R/Rmarkdown
      percentage: 80
    - name: Traditional Statistics & Modeling
      percentage: 80
    - name: JASP
      percentage: 70
    - name: Python/ SQL
      percentage: 40
  # Experience
  disable_experience: false
  experience:
    - company: "EPL Investments"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Data Analyst"
      startdate: Jan 2022
      enddate: present
      featuredpoints:
        - point: Created report using RMarkdown, including data cleaning, wrangling, analysis and visualization. 
        - point: Conducted validation studies in R for customer insight.
        - point: Assisted in design, creation and distribution of surveys to participants.
    - company: "Social Sciences and Humanities Research Council of Canada"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Athlete Motivation Research Lead"
      startdate: Feb 2021
      enddate: Jul 2021
      featuredpoints:
        - point: Assisted in design, creation and distribution of surveys to participants.
        - point: Coordinated and conducted one-on-one athlete interviews.
    - company: "International Center for Olympic Studies"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Social Sciences Research Analyst"
      startdate: Jan 2020
      enddate: July 2021
      featuredpoints:
        - point: Leaded independent qualitative and quantitative research projects.
        - point: Constructed databases to facilitate the analysis of psychometrics and sport analytics.

  # Education
  disable_education: false
  education:
    - degree: "Ph.D"
      branch: "Psychology and ethics"
      university: "Western University"
      startedyear: "2016"
      graduation: "2021"
    - degree: "B.A"
      branch: "Philosophy"
      university: "Université du Québec à Montréal"
      startedyear: "2012"
      graduation: "2015"
    - degree: "Overseas Studies"
      branch: "Logic Specialization"
      university: "Université Paul Valéry Montpellier III"
      startedyear: "2014"
      graduation: "2014"

  # Projects
  disable_projects: false
  projects:
    - name: "Wrangling data in R, with Tinyverse"
      img: /images/project1.png
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Constructed databases to facilitate the analysis of psychometrics and sport analytics.Constructed databases to facilitate the analysis of psychometrics and sport analytics.Constructed databases to facilitate the analysis of psychometrics and sport analytics.Constructed databases to facilitate the analysis of psychometrics and sport analytics.Constructed databases to"
    - name: "Wrangling data in R, with Tinyverse"
      img: /images/project1.png
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Constructed databases to facilitate the analysis of psychometrics and sport analytics.Constructed databases to facilitate the analysis of psychometrics and sport analytics.Constructed databases to facilitate the analysis of psychometrics and sport analytics.Constructed databases to facilitate the analysis of psychometrics and sport analytics.Constructed databases to"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Pan-Am Olympic Qualifier of Carthagena (COL) 2016
      description: Representing Canada while applying for Western University
      img: /images/2016_3.jpg
      url: https://example.com
    - title: University World Championships of Merida (MEX) 2016
      description: Representing Canada during my Masters Degree at Western University
      img: /images/2016_2.jpg
      url: https://example.com
      # url: https://example.com
    - title: Univ. World Championships of Chiangmai (THA) 2014
      description: Representing Canada during my B.A at UQAM
      img: /images/2014_1.jpg
      url: /blog
    - title: International Tournament of Montpellier (FRA) 2014
      description: Personal invitation to compete during an overseas term
      img: /images/2014_4.jpg
      url: /blog

  # Contact
  disable_contact: false
  contact_content: My inbox is always open for questions and conversations. 
  email: "mjgonsalves@protonmail.com"

  # Footer
  socialiconfooter: false
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
