baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
#title: "Hugo-profile"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Examples
      title: Blog posts
      url: /blog
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2

params:
  version: 3
  customCSS: false
  hitext: "Hi there! I'm"

  #favicon: "/images/fav.png"
  #description: "A high performance hugo theme for personal portfolio and blog."

  # home
  disable_home: false
  profile_image: "/images/tike4.png"
  name: "Mikael J. Gonsalves, Ph.D"
  namecolor: ffc107
  profession: "Dr. Psychology & Ethics, Data Analyst"
  github: "https://github.com/MikaelJG"
  gitlab: "https://gitlab.com"
  linkedin: "https://www.linkedin.com/in/mikael-j-gonsalves-ph-d-586260222/"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=H3Icf34AAAAJ&view_op=list_works&sortby=pubdate"
  email: "mailto:mjgonsalves@protonmail.com"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "Hi, again! I'm Mikael a passionate researcher in psychology and data science. Fan of all games, I'm working hard towards a GUXR position!"
  descripe_l2_person: "I work with R/RMarkdown, SPSS, Qualtrics, Tableau and JASP to lead game mixed-methods research projects! Currently learning tricks in python and SQL. You can find my projects [here](/blog)!"
  skills:
    - name: R/Rmarkdown
      percentage: 85
    - name: SPSS
      percentage: 50
    - name: Qualtrics
      percentage: 50
    - name: Tableau
      percentage: 50
    - name: Python/ SQL
      percentage: 40
  # Experience
  disable_experience: false
  experience:
    - company: "EPL Investments"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Data Analyst"
      startdate: Jan 2022
      enddate: present
      featuredpoints:
        - point: Created report using RMarkdown, including data cleaning, wrangling, analysis and visualization. 
        - point: Conducted validation studies in R for customer insight.
        - point: Assisted in design, creation and distribution of surveys to participants.
    - company: "Social Sciences and Humanities Research Council of Canada"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Athlete Motivation Research Lead"
      startdate: Feb 2021
      enddate: Jul 2021
      featuredpoints:
        - point: Assisted in design, creation and distribution of surveys to participants.
        - point: Coordinated and conducted one-on-one athlete interviews.
    - company: "International Center for Olympic Studies"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Social Sciences Research Analyst"
      startdate: Jan 2020
      enddate: July 2021
      featuredpoints:
        - point: Leaded independent qualitative and quantitative research projects.
        - point: Constructed databases to facilitate the analysis of psychometrics and sport analytics.

  # Education
  disable_education: false
  education:
    - degree: "Ph.D"
      branch: "Psychology and Ethics"
      university: "Western University"
      startedyear: "2016"
      graduation: "2021"
    - degree: "B.A"
      branch: "Philosophy"
      university: "Université du Québec à Montréal"
      startedyear: "2012"
      graduation: "2015"
    - degree: "Overseas"
      branch: "Logic Specialization"
      university: "Université Paul Valéry Montpellier III"
      startedyear: "2014"
      graduation: "2014"

  # Projects
  disable_projects: false
  projects:
    - name: "Usability Testing"
      img: /images/project_13.png
      githublink: "https://github.com/"
      featuredlink: "/blog"
      description: "1:1 observational technique where participants perform different tasks. Observers note users’ actions and talks."
    - name: "Heuristics Evaluation"
      img: /images/project_4.png
      githublink: "https://github.com/"
      featuredlink: "/blog"
      description: "Evaluators examine a product’s compliance with recognized principles (‘heuristics’). In this case, game usability principles."
    - name: "Inital Experience Playtest"
      img: /images/project_4.png
      githublink: "https://github.com/"
      featuredlink: "/blog"
      description: "Survey technique assessing attitudes and perceptions of users. Over the first 2 hours of use."

  # Achievements
  disable_achievements: false
  achievements:
    - title: Pan-Am Olympic Qualifier of Carthagena (COL) 2016
      description: On CAN's national team, I finished in the top 10 in pan-american rankings.
      img: /images/2016_3.jpg
      url: https://firstpull.net/2016/06/14/2016-pan-american-championships-rio-olympic-qualification/
    - title: University World Championships of Merida (MEX) 2016
      description: Representing CAN's varsity national team, I finished 5th in the world ranking!
      img: /images/2016_2.jpg
      url: https://www.fisu.net/sport-events/weightlifting/5th-wuc-weightlifting-2016
      # url: https://example.com
    - title: Univ. World Championships of Chiang Mai (THA) 2014
      description: During my B.A at UQAM, I represented CAN's varsity national team for the first time. 
      img: /images/2014_1.jpg
      url: https://www.fisu.net/sport-events/weightlifting/4th-wuc-weightlifting-2014
    - title: International Tournament of Montpellier (FRA) 2014
      description: During an overseas term, I received an invitation for the France Cup.
      img: /images/2014_4.jpg
      url: https://clermont-sports-haltero.fr/phototheque/gallery/randon-2014/

  # Contact
  disable_contact: false
  contact_content: My inbox is always open for questions and conversations. 
  email: "mailto:mjgonsalves@protonmail.com"

  # Footer
  socialiconfooter: false
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
